# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila_datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titular', models.TextField()),
                ('Entradilla', models.TextField()),
                ('Expresiones', models.TextField()),
                ('Medio', models.TextField()),
                ('URLNoticia', models.TextField()),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
